### ISSUE TITLE
Does not work for sites with .htaccess

### ISSUE THREAD

**Issue by styks1111** [geerlingguy/ansible-role-apache-php-fpm#5]
The proxy pass ignores htaccess rewrite rules. User would have to add htaccess rules to the vhost config, would could get super annoying. 

Have you considered using an apache handler instead of proxy pass? 
https://www.linode.com/docs/websites/apache/install-php-fpm-and-apache-on-debian-8

**Comment by Luwdo** [comment]
This might be related to my issue here:
https://github.com/geerlingguy/ansible-role-apache-php-fpm/issues/7
